apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-boilerplate
spec:
  secretName: api-boilerplate-crt-secret
  dnsNames:
    - api-boilerplate.<DOMAINNAME>.com
    - www.api-boilerplate.<DOMAINNAME>.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: api-boilerplate.<DOMAINNAME>.com
