apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-boilerplate
spec:
  secretName: api-boilerplate-crt-secret
  dnsNames:
  - api-boilerplate.brainenterprise.ca
  - www.api-boilerplate.brainenterprise.ca
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io
  commonName: api-boilerplate.brainenterprise.ca
