name: Test Deploy
on:
  push:
    branches:
      - master

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Decrypt File
        run: |
          mkdir $HOME/.kube
          gpg --quiet --batch --yes --decrypt --passphrase ${{ secrets.DECRYPT_PASSPHRASE }} --output $HOME/.kube/config-travisci-sa config-travisci-sa.gpg

      - name: Download Kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Setup Kubeconfig
        run: |
          export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config-travisci-sa
          kubectl config view --flatten > $HOME/.kube/config
          kubectl config set-context --current --user=travisci-sa

      - name: Build and Test Frontend
        run: |
          docker build -t tempimage -f ./frontend/Dockerfile.dev ./frontend
          docker run -w=/app tempimage npm test -- --coverage

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          DOCKERHUB_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        with:
          username: $DOCKERHUB_HUB_USERNAME
          password: $DOCKER_HUB_TOKEN

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Push Frontend Image
        id: frontend_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.next
          push: true
          tags: duncanbrain/boiler-api-frontend:latest,duncanbrain/boiler-api-frontend:$GITHUB_SHA

      - name: Image digest
        run: echo ${{ steps.frontend_build.outputs.digest }}

      - name: Build Push API Image
        id: api_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: duncanbrain/boiler-api-api:latest,duncanbrain/boiler-api-api:$GITHUB_SHA

      - name: Image digest
        run: echo ${{ steps.api_build.outputs.digest }}

      - name: Deploy to Cluster
        run: |
          kubectl --kubeconfig=$HOME/.kube/config apply -f k8s
          kubectl --kubeconfig=$HOME/.kube/config set image deployment/frontend-deployment frontend=duncanbrain/boiler-api-frontend:$SHA
          kubectl --kubeconfig=$HOME/.kube/config set image deployment/api-deployment api=duncanbrain/boiler-api-api:$SHA
