name: Test And Deploy
on:
  push:
    branches:
      - master

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build And Test Frontend
        run: |
          docker build -t temp-image -f ./frontend/Dockerfile.dev ./frontend
          docker run temp-image npm test -- --coverage

  deploy-docker:
    needs: [test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Login To Docker Hub
        uses: docker/login-action@v1
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        with:
          username: "$USER"
          password: "$TOKEN"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Push Frontend Image
        uses: docker/build-push-action@v2
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.next
          push: true
          tags: "$USER"/boiler-api-frontend:latest,"$USER"/boiler-api-frontend:${{ github.sha }}

      - name: Build Push API Image
        uses: docker/build-push-action@v2
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: "$USER"/boiler-api-api:latest,"$USER"/boiler-api-api:${{ github.sha }}

  deploy-do-kubernetes:
    needs: [test-frontend, deploy-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Download Kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Setup Kubeconfig
        env:
          PASSPHRASE: ${{ secrets.DECRYPT_PASSPHRASE }}
        run: |
          mkdir $HOME/.kube
          gpg --quiet --batch --yes --decrypt --passphrase "$PASSPHRASE" --output $HOME/.kube/config config-travisci-sa.gpg
          kubectl config set-context --current --user=travisci-sa

      - name: Install Ingress Nginx On Digital Ocean Cluster
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/do/deploy.yaml

      - name: Deploy App To Cluster
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          kubectl --kubeconfig=$HOME/.kube/config apply -f k8s
          kubectl --kubeconfig=$HOME/.kube/config set image deployment/frontend-deployment frontend="$USER"/boiler-api-frontend:${{ github.sha }}
          kubectl --kubeconfig=$HOME/.kube/config set image deployment/api-deployment api="$USER"/boiler-api-api:${{ github.sha }}
